"""End-to-end pipeline orchestrator for one (event, state) slice.

Glues together: ECI fetch → parse partywise → fetch each constituencywise →
parse + map → compose ResultSummary → write the canonical store. This is
the only module allowed to import from ``core/``, ``sources/``, AND
``pipeline/compose`` together.

Output (PR-O.3b-main / TODO row ``1.8b-writers-b-main``):

    datasets/elections/election_results.parquet   # canonical UPSERT
    datasets/taxonomy/sources.parquet             # canonical UPSERT
    datasets/elections/dim_*.parquet              # canonical dimension UPSERTs
    datasets/manifest.json                        # regenerated by the writer

The legacy per-state JSON shards that used to live here are retired —
``results/<n>.json``, ``result.summary.json``, and ``parties.json`` are
no longer written by the live pipeline. The in-memory ``RunResult`` still
exposes ``constituencies`` / ``summary`` / ``parties`` so the CSV emitter
(``yen_gov.emit.csv_bundle``, PR-O.3a) can consume them directly. The
sibling SQLite emitter retired in PR-R.3 (TODO row 1.8e). The one-shot
historical backfill driver ``canonical_eci_backfill.backfill_elections``
still reads the existing on-disk JSON corpus until row 1.8b-ii (PR-O.4)
deletes those files.

Per CLAUDE.md §6 fail-loud: a single AC failure aborts the run. We don't ship
a partial canonical write that silently elides constituencies.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from yen_gov.canonical.adapters.eci.identity import parse_period_label
from yen_gov.canonical.adapters.eci.party_lookup import (
    load_party_lookup,
    party_alliance_dim_rows,
    party_dim_rows,
)
from yen_gov.canonical.envelope import (
    BatchEnvelope,
    PartyAllianceDimRow,
    PartyDimRow,
)
from yen_gov.canonical.writer import write_batch
from yen_gov.core.http import Fetcher
from yen_gov.core.models import (
    ConstituencyResult,
    PartiesSnapshot,
    PartyEntry,
    ResultSummary,
    SourceRef,
)
from yen_gov.pipeline.canonical_eci_backfill import build_slice_envelope
from yen_gov.pipeline.compose import (
    compose_result_summary,
    party_lookup_from_partywise,
    reconcile_winners_against_partywise,
)
from yen_gov.sources.eci.constituencywise import (
    parse_constituencywise,
    to_constituency_result,
)
from yen_gov.sources.eci.partywise import PartywiseSnapshot, parse_partywise
from yen_gov.sources.eci.urls import constituencywise_url, partywise_state_url


@dataclass(frozen=True)
class RunPaths:
    """Paths produced by a live pipeline run.

    Post-PR-O.3b-main the only emitted artifact is the canonical Parquet
    (plus the writer's sibling dim Parquets + the regenerated manifest,
    which always live at canonical paths and so don't need pointers).
    Callers that previously read ``result.paths.parties`` /
    ``.summary`` / ``.results_dir`` must switch to the in-memory
    ``RunResult.parties`` / ``.summary`` / ``.constituencies``.
    """
    canonical_parquet: Path


@dataclass(frozen=True)
class RunResult:
    snapshot: PartywiseSnapshot
    constituencies: list[ConstituencyResult]
    summary: ResultSummary
    parties: PartiesSnapshot
    paths: RunPaths


def run_state_slice(
    *,
    event_id: str,
    state_code: str,
    datasets_root: Path,
    fetcher: Fetcher,
    top_n: int,
    collapse_others: bool,
) -> RunResult:
    """Fetch + parse + compose + write one (event, state) slice into the canonical store.

    ``datasets_root`` MUST be the repo's ``datasets/`` directory — the
    writer rewrites ``elections/election_results.parquet`` and the manifest
    underneath it.
    """
    snapshot, snapshot_src = _fetch_partywise(fetcher, event_id, state_code)
    lookup = party_lookup_from_partywise(snapshot)

    constituencies: list[ConstituencyResult] = []
    constituency_sources: list[SourceRef] = []
    for n in range(1, snapshot.total_seats + 1):
        cr, src = _fetch_constituency(
            fetcher, event_id=event_id, state_code=state_code, eci_no=n,
            top_n=top_n, collapse_others=collapse_others, party_lookup=lookup,
        )
        constituencies.append(cr)
        constituency_sources.append(src)

    summary = compose_result_summary(
        election=event_id, state=state_code, body="AC",
        partywise=snapshot, constituencies=constituencies,
        sources=[snapshot_src, *constituency_sources],
    )
    reconcile_winners_against_partywise(
        partywise=snapshot, constituencies=constituencies,
    )

    parties = parties_snapshot_from_partywise(
        snapshot, election=event_id, sources=[snapshot_src],
    )

    canonical_path = _write_canonical_slice(
        datasets_root=datasets_root,
        event_id=event_id,
        state_code=state_code,
        constituencies=constituencies,
    )

    return RunResult(
        snapshot=snapshot,
        constituencies=constituencies,
        summary=summary,
        parties=parties,
        paths=RunPaths(canonical_parquet=canonical_path),
    )


def _write_canonical_slice(
    *,
    datasets_root: Path,
    event_id: str,
    state_code: str,
    constituencies: list[ConstituencyResult],
) -> Path:
    """Build a BatchEnvelope from the in-memory slice and UPSERT it.

    Mirrors the per-event envelope assembly that
    ``canonical_eci_backfill.backfill_elections`` performs for the on-disk
    backfill path — the canonical-write contract is the same regardless of
    whether the source is a live ECI fetch or a re-parse of historical
    JSONs. The party dim is seeded from the global ``parties.json``
    registry; the writer UPSERTs so a later state-slice write for the same
    event is a no-op on the dim side.
    """
    period = parse_period_label(event_id)
    party_lookup = load_party_lookup(datasets_root)

    rows, sources_by_id, _unresolved, candidate_dims, ac_dims = build_slice_envelope(
        constituencies=constituencies,
        state_code=state_code,
        period=period,
        party_lookup=party_lookup,
    )

    first_source_id = sorted(sources_by_id.keys())[0] if sources_by_id else ""
    party_dim_payload = (
        [PartyDimRow(**r) for r in party_dim_rows(party_lookup, source_id=first_source_id)]
        if first_source_id
        else []
    )
    party_alliance_payload = (
        [
            PartyAllianceDimRow(**r)
            for r in party_alliance_dim_rows(party_lookup, source_id=first_source_id)
        ]
        if first_source_id
        else []
    )

    envelope = BatchEnvelope(
        target_family="elections",
        schema_version="1.0",
        source_rows=sorted(sources_by_id.values(), key=lambda s: s.source_id),
        observation_rows=rows,
        candidate_dim_rows=candidate_dims,
        ac_dim_rows=ac_dims,
        party_dim_rows=party_dim_payload,
        party_alliance_dim_rows=party_alliance_payload,
    )
    result = write_batch(envelope, datasets_root)
    return result.observations_path


def _fetch_partywise(
    fetcher: Fetcher, event_id: str, state_code: str,
) -> tuple[PartywiseSnapshot, SourceRef]:
    url = partywise_state_url(event_id, state_code)
    fr = fetcher.fetch(url)
    snapshot = parse_partywise(fr.content)
    return snapshot, SourceRef(url=fr.url, fetched_at=fr.fetched_at)


def _fetch_constituency(
    fetcher: Fetcher, *, event_id: str, state_code: str, eci_no: int,
    top_n: int, collapse_others: bool,
    party_lookup: dict[str, tuple[str, str | None]],
) -> tuple[ConstituencyResult, SourceRef]:
    url = constituencywise_url(event_id, state_code, eci_no)
    fr = fetcher.fetch(url)
    raw = parse_constituencywise(fr.content)
    src = SourceRef(url=fr.url, fetched_at=fr.fetched_at)
    cr = to_constituency_result(
        raw,
        election=event_id, state=state_code, body="AC", eci_no=eci_no,
        top_n=top_n, collapse_others=collapse_others,
        sources=[src], party_lookup=party_lookup,
    )
    return cr, src


def parties_snapshot_from_partywise(
    snapshot: PartywiseSnapshot, *, election: str, sources: list[SourceRef],
) -> PartiesSnapshot:
    # Drop rows whose ECI numeric code we couldn't extract — party.schema.json
    # requires it. Those parties will still be visible in result.summary.json
    # via party_short, but won't appear in the canonical parties roster until
    # a future adapter (e.g. notification.eci.gov.in) supplies missing codes.
    entries = [
        PartyEntry(
            eci_code=row.eci_code,
            short_name=row.short_name,
            full_name=row.full_name,
        )
        for row in snapshot.parties
        if row.eci_code is not None
    ]
    if not entries:
        raise ValueError("partywise snapshot yielded zero parties with ECI codes")
    return PartiesSnapshot(sources=sources, election=election, parties=entries)
