// PR-4 of TODO/20260612-party-rendering-and-party-pages-plan.md.
//
// `loadPartyDetail(party_id)` assembles the per-party detail page
// view-model (header + KPI strip + LS/VS history + strongholds +
// metadata) by reading the backend-derived party-page marts under
// `datasets/data/marts/party_pages/` plus the parties.csv metadata via
// the PR-1 `loadPartyMeta` accessor.
//
// The marts are generated by:
//
//   python -m yen_gov derive-party-pages --root .
//
// and validated by a Tier-B freshness signature. The browser MUST NOT
// read `datasets/data/datapoints/electoral/*.csv` for a party detail
// page: that corpus is ~177 MB and belongs in the local backend
// pipeline, not in a citizen route.

import { query, registerCsvFile } from "../duckdb";
import { csvColumnsClause } from "../canonical/csv-columns";
import { DATA_BASE } from "../paths";
import { cleanNote } from "../methodology/clean-note";
import { slugify } from "../slug";
import { link } from "../links";
import { states } from "../states.svelte";
import {
  fetchElectionEvents,
  defaultEventForState,
  type ElectionEventsCatalogue,
} from "../election-events";
import {
  loadConstituencyRows,
  resolveConstituencyFromRows,
  type ConstituencyEntity,
} from "../elections/constituency-lookup";
import { loadPartyMeta, type PartyMeta } from "./parties";
import {
  loadPartyCurrentStrength,
  type PartyCurrentStrength,
} from "./party-current-strength";
import {
  loadPartyAllianceContext,
  type PartyAllianceContext,
} from "./party-alliance-context";
import {
  buildPartyProvenance,
  loadSourceLookup,
  splitSourceIds,
  type PartyProvenance,
} from "./party-sources";

/** Party-page mart paths (repo-relative for columns.json lookup +
 *  runtime URL for DuckDB-WASM HTTP reads). */
const PARTY_HISTORY_REL = "datasets/data/marts/party_pages/history.csv";
const PARTY_HISTORY_URL = `${DATA_BASE}/data/marts/party_pages/history.csv`;
const PARTY_STRONGHOLDS_REL = "datasets/data/marts/party_pages/strongholds.csv";
const PARTY_STRONGHOLDS_URL = `${DATA_BASE}/data/marts/party_pages/strongholds.csv`;
/** PR-9: alliance ledger - read by the loader to surface the
 *  per-party set of distinct source_ids the Alliance Context card
 *  consumes. The alliance view-model (`party-alliance-context.ts`)
 *  does NOT surface source_ids on its public types today; we pull
 *  them here so the provenance envelope can attribute the card
 *  without breaking the alliance VM contract. */
const PARTY_ALLIANCES_REL = "datasets/data/entities/party_alliances.csv";
const PARTY_ALLIANCES_URL = `${DATA_BASE}/data/entities/party_alliances.csv`;

/** PR-10: methodology-breaks catalogue URL. The catalogue ships as a
 *  hand-authored JSON under `datasets/taxonomy/` (NOT a derived mart);
 *  the LS chart on /parties/<slug> filters the rows by
 *  `methodology_version` to surface only the LS-relevant delim breaks. */
const METHODOLOGY_BREAKS_URL = `${DATA_BASE}/taxonomy/methodology_breaks.json`;

/** Subset of `lspc-delim-*` methodology_versions PR-10 renders as
 *  vertical markers on the Lok Sabha DualAxisBarLine chart. Per the
 *  PR-10 brief (Jony 1d): the 2 pre-1999 frame_change rows surfaced
 *  by PR-8 #1003's new LS coverage (1962/1989/1991/1996/1998 cycles).
 *  The 2008 delim break is NOT in this list - it lives in the
 *  post-1998 era already covered before PR-8 and is a different
 *  signal class. Future agents adding markers SHOULD extend this
 *  set rather than relax it to a broader filter, so the LS chart's
 *  marker grammar stays explicit. */
export const LS_METHODOLOGY_VERSIONS: ReadonlySet<string> = new Set([
  "lspc-delim-1967",
  "lspc-delim-1976",
]);

/** PR-10: one row of the methodology-breaks catalogue exposed on the
 *  view-model. Mirrors `datasets/schemas/methodology-break.schema.json`
 *  v1.0 verbatim - any future schema bump (additive) lands here too.
 *  Optional fields kept optional so a v1.x reader survives a v2.0
 *  schema without panicking. */
export interface MethodologyBreakRow {
  methodology_version: string;
  at_year: number;
  at_period_seq: number;
  kind:
    | "rebase"
    | "definition_change"
    | "frame_change"
    | "coverage_change"
    | "reclassification";
  note: string;
  publisher_url?: string | null;
  supersedes_methodology_version?: string | null;
}

/** Wire shape of `datasets/taxonomy/methodology_breaks.json` per
 *  `datasets/schemas/methodology-break.schema.json` v1.0. */
interface MethodologyBreaksCatalogue {
  $schema?: string;
  $schema_version?: string;
  methodology_breaks: MethodologyBreakRow[];
}

/** One contested election cycle for a party in one body. */
export interface PartyHistoryPoint {
  /** 4-digit polling year. */
  year: number;
  /** Canonical event id (e.g. `AcGenApr2021`, `LsGenMay2024`). */
  period_label: string;
  /** Number of seats won; 0 when the party contested but won none. */
  seats: number;
  /** Vote-share percentage (0..100); null when the cycle has no
   *  `party-vote-share-pct` row (rare; defensive). */
  vote_share_pct: number | null;
  /** Number of constituencies the party fielded a candidate in;
   *  null when the cycle has no `party-contested-acs` (VS) or
   *  `party-contested-pcs` (LS) row. */
  contested: number | null;
  /** PR-9: distinct source_ids backing this cycle (union across
   *  the per-state rows the mart aggregator collapsed into this
   *  point). Each entry MUST be present in
   *  `datasets/data/entities/source.csv`; the
   *  `party-page-provenance.test.ts` contract test enforces this
   *  mechanically. Empty `[]` is illegal once a point lands on the
   *  view-model - `historyPointFromMart` returns null for rows with
   *  no source_ids on the underlying mart row (Holy Law #9). */
  source_ids: string[];
}

/** One stronghold constituency for a party, scoped to one body. */
export interface PartyStronghold {
  /** Constituency entity_id (e.g. `IN-AC-2008-S22-167`). */
  entity_id: string;
  /** Citizen-readable constituency name from electoral.csv. Empty
   *  string when the JOIN misses (defensive). */
  constituency_name: string;
  /** LGD state slug derived from the entity_id; used for the linkout
   *  in future PRs. v1 ships text-only per the brief. */
  state: string;
  /** Total wins by this party in this constituency (across all
   *  events covered by the canonical store). */
  wins: number;
  /** Total elections held in this constituency (i.e. cycles where
   *  ANY winner_party_id row exists for this entity_id), regardless
   *  of whether this party contested. */
  contested: number;
  /** Per-event outcome chronologically (oldest first). `"W"` when
   *  this party won that event, `"L"` otherwise (loss OR no-contest). */
  results: ("W" | "L")[];
  /** PR-7 (TODO/20260615-party-page-citizen-fixes-plan.md): year
   *  of the MOST RECENT win by this party in this constituency.
   *  Renders as the "last YYYY" suffix on the one-line stronghold
   *  tally. Null when the legacy in-memory fold path (test-only)
   *  emits a stronghold; the production loader always populates
   *  from the mart's `last_won_year` column. */
  last_won_year: number | null;
  /** PR-9: distinct source_ids backing this stronghold (union
   *  across the per-event winner rows that contributed to the W/L
   *  sparkline). Pipe-delimited on the mart; split + deduped at
   *  the loader boundary. */
  source_ids: string[];
  /** PR-8b D8a: name-slug of `constituency_name` for callers that
   *  need to build the constituency leaf URL. Non-null only when the
   *  `(state, kind, slug)` triple resolves against the canonical
   *  electoral.csv entity tier AT THE LATEST DELIM cohort. Null
   *  when no current-delim entity matches (e.g. retired ACs from
   *  pre-2008 cohorts) - the row is then unclickable on the page. */
  pc_slug: string | null;
  /** PR-8b D8a: full in-app URL to the constituency leaf when a
   *  current-delim entity exists AND a target event_id is available
   *  for this body (LS uses `current_strength.parliament_latest`,
   *  VS uses the per-state default assembly event). Null otherwise.
   *  When null the stronghold row renders as a plain `<span>`; when
   *  non-null it renders as `<a href={href}>`. */
  href: string | null;
}

/** Aggregate KPI totals for the header strip. */
export interface PartyTotals {
  /** Sum of party-seats-won across every Lok Sabha cycle. */
  ls_seats: number;
  /** Sum of party-seats-won across every Vidhan Sabha cycle. */
  vs_seats: number;
  /** Number of cycles (LS + VS) where this party contested >0 or
   *  won >0. */
  elections_contested: number;
  /** Earliest polling year on file across ALL contested cycles
   *  (LS + VS). 0 when no cycles. */
  first_year: number;
  /** Latest polling year on file. 0 when no cycles. */
  last_year: number;
  /** Peak Lok Sabha seats won in any single cycle. 0 when no LS. */
  peak_ls_seats: number;
  /** Year of the peak LS cycle. 0 when no LS. */
  peak_ls_year: number;
  /** Peak Vidhan Sabha seats won in any single cycle. 0 when no VS. */
  peak_vs_seats: number;
  /** Year of the peak VS cycle. 0 when no VS. */
  peak_vs_year: number;
}

/** Per-party detail page view-model. */
export interface PartyDetailViewModel {
  metadata: PartyMeta;
  /** Lok Sabha history (chronological ascending). Empty for parties
   *  with no parliamentary contests. */
  ls_history: PartyHistoryPoint[];
  /** Vidhan Sabha history (chronological ascending). Empty for
   *  parties that only contest parliament (rare). */
  vs_history: PartyHistoryPoint[];
  /** Top-10 LS strongholds by wins descending. Empty when no LS
   *  presence. */
  ls_strongholds: PartyStronghold[];
  /** Top-10 VS strongholds by wins descending. Empty when no VS
   *  presence. */
  vs_strongholds: PartyStronghold[];
  /** Aggregate KPI totals. */
  totals: PartyTotals;
  /** PR-10: methodology-break rows the LS chart surfaces as vertical
   *  markers. Empty when the catalogue carries no
   *  `LS_METHODOLOGY_VERSIONS` row (defensive; today's catalogue
   *  always carries the 2 lspc-delim rows). The view-model carries
   *  these on every party (LS or VS only) because the chart-side
   *  filter is cheap and avoids per-route branching at the consumer. */
  ls_methodology_breaks: MethodologyBreakRow[];
  /** PR-7: "Where this party sits today" Current Strength strip
   *  view-model. Null for sentinel parties (NOTA / UNK) or for
   *  parties with no contested history at all - the consumer
   *  (`PartyCurrentStrength.svelte`) renders nothing when null. */
  current_strength: PartyCurrentStrength | null;
  /** PR-8: "Who they ride with" Alliance Context strip view-model.
   *  Null for sentinel parties (NOTA / UNK), for Independent
   *  (parties.IN.IND), and for parties with no alliance rows in
   *  `datasets/data/entities/party_alliances.csv`. The consumer
   *  (`PartyAllianceContext.svelte`) renders nothing when null. */
  alliance_context: PartyAllianceContext | null;
  /** PR-9: distinct source_ids backing the alliance card. Empty
   *  `[]` when `alliance_context` is null. Derived by a separate
   *  DuckDB query against `datasets/data/entities/party_alliances.csv`
   *  in the loader (the per-state alliance VM rows do not surface
   *  source_id today; pulling it here keeps the alliance VM
   *  contract untouched). */
  alliance_source_ids: string[];
  /** PR-9: distinct source_ids backing the current-strength card.
   *  Empty `[]` when `current_strength` is null. Derived from the
   *  latest LS cycle's source_ids plus the latest VS cycle per
   *  state - the same set of rows the current-strength loader
   *  aggregates. */
  current_strength_source_ids: string[];
  /** PR-9: Holy Law #9 envelope. Carries the 5 per-card coverage
   *  badges + the bottom-of-page source-pill strip. Built by
   *  `buildPartyProvenance` from the populated VM + the
   *  source.csv lookup. THROWS at load time when any rendered
   *  card has data but resolves zero source_ids (STOP-AND-SURFACE
   *  per CLAUDE.md section 10). */
  provenance: PartyProvenance;
}

/** Raw history-row shape from DuckDB. */
interface RawHistoryRow {
  year: number | bigint | null;
  period_label: string | null;
  indicator_id: string | null;
  value_numeric: number | null;
}

/** Raw stronghold-row shape from DuckDB. */
interface RawStrongholdRow {
  entity_id: string | null;
  period_label: string | null;
  winner_party_id: string | null;
}

/** Raw party-page history mart row. */
interface RawPartyHistoryMartRow {
  body: string | null;
  period_label: string | null;
  year: number | bigint | null;
  seats: number | bigint | null;
  vote_share_pct: number | null;
  contested: number | bigint | null;
  /** PR-9: per-cycle source_ids derived via
   *  STRING_AGG(DISTINCT source_ids, '|') across the per-state
   *  rows that fold into one (body, period_label) point. The mart
   *  carries a single src-XXXX per row, so this is effectively a
   *  pipe-delimited dedupe across states. */
  source_ids: string | null;
}

/** Raw party-page stronghold mart row. */
interface RawPartyStrongholdMartRow {
  body: string | null;
  rank: number | bigint | null;
  entity_id: string | null;
  constituency_name: string | null;
  state: string | null;
  wins: number | bigint | null;
  contested: number | bigint | null;
  /** PR-7: year of the most recent W per (party, entity_id);
   *  surfaced as the "last YYYY" suffix on the one-line stronghold
   *  tally. The writer always emits a non-null integer (computed
   *  via `max(year for event in events if winner == party_id)`
   *  with `wins > 0` guaranteed at the same row scope). */
  last_won_year: number | bigint | null;
  results: string | null;
  /** PR-9: pipe-delimited source_ids per stronghold (the writer
   *  emits the union of every winner-cycle's source_ids; see
   *  `derive-party-pages` in the backend). */
  source_ids: string | null;
}

/** PR-9: raw alliance ledger row reduced to the source_id column.
 *  party_alliances.csv carries one row per (party_id, event_id,
 *  state); we DISTINCT the source_id to surface the unique citation
 *  set the alliance card consumes. */
interface RawAllianceSourceRow {
  source_id: string | null;
}

function intOrNull(value: number | bigint | null | undefined): number | null {
  if (value == null) return null;
  if (typeof value === "bigint") return Number(value);
  return Number.isFinite(value) ? Math.trunc(value) : null;
}

function numOrNull(value: number | null | undefined): number | null {
  if (value == null) return null;
  return Number.isFinite(value) ? Number(value) : null;
}

/** Pure: classify a period_label into the body it belongs to. */
export function bodyForPeriodLabel(
  period_label: string,
): "ls" | "vs" | null {
  if (period_label.startsWith("Ls")) return "ls";
  if (period_label.startsWith("Ac")) return "vs";
  return null;
}

/** Pure: extract the SHORT (party_id tail) from a `parties.IN.<X>` id.
 *  The on-disk `entity_id` pattern uses the SHORT verbatim
 *  (e.g. `IN-S22-AcGenApr2021-PARTY-DMK` for `parties.IN.DMK`). */
export function partyIdTail(party_id: string): string {
  const dot = party_id.lastIndexOf(".");
  return dot >= 0 ? party_id.slice(dot + 1) : party_id;
}

/** Recognised history indicator ids; rows carrying anything else
 *  are silently ignored at the fold boundary. ``party-contested-acs``
 *  and ``party-contested-pcs`` are SIBLINGS — both fold to the same
 *  ``contested`` slot. The only semantic difference is the grain
 *  (ACs for VS events, PCs for LS events); the period_label prefix
 *  already discriminates which body a cycle belongs to, so there is
 *  no per-grain dispatch in the fold logic. */
const HISTORY_INDICATORS = new Set<string>([
  "party-seats-won",
  "party-vote-share-pct",
  "party-contested-acs",
  "party-contested-pcs",
]);

/** Pure: split a flat list of history rows into one
 *  `PartyHistoryPoint` per `period_label`. Rows arrive 3-per-cycle
 *  (one for seats, one for vote share, one for contested); we fold
 *  by period_label. Output is sorted chronologically by year then
 *  period_label as a tie-breaker (multiple bye-elections in one
 *  year keep a deterministic order). Rows with no period_label,
 *  no year, or an unrecognised indicator_id are silently dropped
 *  before they can introduce a phantom event into the fold. */
export function foldHistoryRows(
  rows: RawHistoryRow[],
): PartyHistoryPoint[] {
  const byEvent = new Map<string, PartyHistoryPoint>();
  for (const r of rows) {
    if (!r.period_label || !r.indicator_id) continue;
    if (!HISTORY_INDICATORS.has(r.indicator_id)) continue;
    const year = intOrNull(r.year);
    if (year == null) continue;
    const value = numOrNull(r.value_numeric);
    const existing = byEvent.get(r.period_label) ?? {
      year,
      period_label: r.period_label,
      seats: 0,
      vote_share_pct: null,
      contested: null,
      // Legacy fold path (test-only); the production loader uses
      // `historyPointFromMart` which surfaces real per-cycle
      // source_ids from the mart. The fold helper's inputs do not
      // carry source_ids today, so we surface an empty list -
      // callers of the legacy path are not provenance-bearing.
      source_ids: [],
    };
    switch (r.indicator_id) {
      case "party-seats-won":
        existing.seats = value ?? 0;
        break;
      case "party-vote-share-pct":
        existing.vote_share_pct = value;
        break;
      case "party-contested-acs":
      case "party-contested-pcs":
        existing.contested = value == null ? null : Math.trunc(value);
        break;
    }
    byEvent.set(r.period_label, existing);
  }
  const out = [...byEvent.values()];
  out.sort((a, b) => {
    if (a.year !== b.year) return a.year - b.year;
    return a.period_label.localeCompare(b.period_label);
  });
  return out;
}

/** Month-name lookup so a sort key can put `AcGenApr2021` after
 *  `AcGenJan1989` chronologically (alphabetical sort would yield
 *  Apr < Feb < Jan, which is wrong). */
const MONTH_INDEX: Record<string, number> = {
  Jan: 1,
  Feb: 2,
  Mar: 3,
  Apr: 4,
  May: 5,
  Jun: 6,
  Jul: 7,
  Aug: 8,
  Sep: 9,
  Oct: 10,
  Nov: 11,
  Dec: 12,
};

/** Pure: derive a chronological sort key from an ECI event id
 *  (e.g. `AcGenApr2021` -> `2021-04`). Falls back to the raw label
 *  when no `<Mon><Year>` suffix matches so the sort stays
 *  deterministic. Exported for test coverage. */
export function chronologicalSortKey(period_label: string): string {
  const m = period_label.match(/([A-Z][a-z]{2})(\d{4})$/);
  if (!m) return `9999-99-${period_label}`;
  const month = MONTH_INDEX[m[1]!] ?? 99;
  return `${m[2]}-${String(month).padStart(2, "0")}`;
}

/** Pure: fold stronghold rows into per-constituency aggregates.
 *  `target_party_id` is the party we're scoring against. For each
 *  (entity_id), count `wins` (rows where this party is the winner) +
 *  `contested` (total events with ANY winner). The `results[]`
 *  sparkline is per-event chronologically; per-event we emit "W"
 *  if this party won OR "L" otherwise. */
export function foldStrongholdRows(
  rows: RawStrongholdRow[],
  target_party_id: string,
  entity_name_lookup: Map<string, string>,
  entity_state_lookup: Map<string, string>,
): PartyStronghold[] {
  // First pass: group all rows by entity_id, sort by chronological
  // (year, month) so the sparkline reads chronologically.
  const byEntity = new Map<
    string,
    { period_label: string; winner_party_id: string }[]
  >();
  for (const r of rows) {
    if (!r.entity_id || !r.period_label) continue;
    const winner = (r.winner_party_id ?? "").trim();
    const list = byEntity.get(r.entity_id) ?? [];
    list.push({ period_label: r.period_label, winner_party_id: winner });
    byEntity.set(r.entity_id, list);
  }
  const out: PartyStronghold[] = [];
  for (const [entity_id, events] of byEntity) {
    events.sort((a, b) =>
      chronologicalSortKey(a.period_label).localeCompare(
        chronologicalSortKey(b.period_label),
      ),
    );
    let wins = 0;
    const results: ("W" | "L")[] = [];
    for (const e of events) {
      const isWin = e.winner_party_id === target_party_id;
      if (isWin) wins += 1;
      results.push(isWin ? "W" : "L");
    }
    // Only surface strongholds where the party has at least one win;
    // a 0-win row is not a stronghold and would noise the top-10.
    if (wins === 0) continue;
    out.push({
      entity_id,
      constituency_name: entity_name_lookup.get(entity_id) ?? "",
      state: entity_state_lookup.get(entity_id) ?? "",
      wins,
      contested: events.length,
      // Legacy fold path: `RawStrongholdRow` does not carry year;
      // the helper is test-only and its callers are not
      // recency-bearing. Production loader populates from the mart.
      last_won_year: null,
      results,
      // Legacy fold path (test-only); see `foldHistoryRows` note.
      source_ids: [],
      // PR-8b D8a: legacy fold path does not derive clickability;
      // production loader sets these via `attachStrongholdLink`.
      pc_slug: null,
      href: null,
    });
  }
  // Top-10 by wins desc, then by win-rate desc (so a 5-of-5 sweeper
  // outranks a 5-of-10 streaky party), then by entity_id for
  // determinism.
  out.sort((a, b) => {
    if (a.wins !== b.wins) return b.wins - a.wins;
    const winRateDiff = b.wins / b.contested - a.wins / a.contested;
    if (Math.abs(winRateDiff) > 1e-9) return winRateDiff;
    return a.entity_id.localeCompare(b.entity_id);
  });
  return out.slice(0, 10);
}

/** Pure: compute the aggregate KPI totals from the LS + VS history. */
export function computeTotals(
  ls_history: PartyHistoryPoint[],
  vs_history: PartyHistoryPoint[],
): PartyTotals {
  let ls_seats = 0;
  let peak_ls_seats = 0;
  let peak_ls_year = 0;
  for (const p of ls_history) {
    ls_seats += p.seats;
    if (p.seats > peak_ls_seats) {
      peak_ls_seats = p.seats;
      peak_ls_year = p.year;
    }
  }
  let vs_seats = 0;
  let peak_vs_seats = 0;
  let peak_vs_year = 0;
  for (const p of vs_history) {
    vs_seats += p.seats;
    if (p.seats > peak_vs_seats) {
      peak_vs_seats = p.seats;
      peak_vs_year = p.year;
    }
  }
  const all = [...ls_history, ...vs_history];
  const contested_cycles = all.filter(
    (p) => p.seats > 0 || (p.contested ?? 0) > 0,
  );
  const elections_contested = contested_cycles.length;
  let first_year = 0;
  let last_year = 0;
  if (contested_cycles.length > 0) {
    first_year = contested_cycles.reduce(
      (acc, p) => Math.min(acc, p.year),
      contested_cycles[0]!.year,
    );
    last_year = contested_cycles.reduce(
      (acc, p) => Math.max(acc, p.year),
      contested_cycles[0]!.year,
    );
  }
  return {
    ls_seats,
    vs_seats,
    elections_contested,
    first_year,
    last_year,
    peak_ls_seats,
    peak_ls_year,
    peak_vs_seats,
    peak_vs_year,
  };
}

/** Pure: filter a methodology-breaks catalogue to the rows the LS
 *  chart on /parties/<slug> renders as vertical markers. Pinned to
 *  `LS_METHODOLOGY_VERSIONS`; rows the catalogue carries but the LS
 *  chart does NOT surface (other indicator families' breaks; the
 *  2008 delim break already covered by the pre-PR-8 LS window) are
 *  silently dropped. Sort order is `at_year` ascending so the first
 *  vertical marker the citizen sees is also the first (chronological)
 *  break - the consumer renders footnote numbers 1) 2) ... in that
 *  order without re-sorting.
 *
 *  PR-2 of TODO/20260614-party-page-reimagination-plan.md scrubs
 *  the `note` field through `cleanNote` at this boundary so any
 *  operator-narrative leak that survives the on-disk hand-scrub
 *  (the source-of-truth fix) gets filtered before reaching the
 *  citizen-facing tooltip. Idempotent on already-clean text. */
export function pickLsMethodologyBreaks(
  rows: readonly MethodologyBreakRow[],
): MethodologyBreakRow[] {
  const out = rows
    .filter((r) => LS_METHODOLOGY_VERSIONS.has(r.methodology_version))
    .map((r) => ({ ...r, note: cleanNote(r.note) }));
  out.sort((a, b) => a.at_year - b.at_year);
  return out;
}

/** Pure: keep only the methodology-break rows that fall strictly
 *  INSIDE the party's LS chart year domain - i.e. `at_year > first`
 *  AND `at_year <= last` where first/last are the earliest / latest
 *  LS cycle years for the party. Mirrors the chart-side filter in
 *  `DualAxisBarLine.computeMethodologyBreakMarkers` so the caption
 *  below the chart agrees with the markers rendered above it (a party
 *  like BJP whose first LS cycle is 1984 sees zero markers AND zero
 *  caption; DMK whose first LS cycle is 1962 sees both markers AND
 *  both caption lines). Returns empty when the party has no LS
 *  history (defensive; the caller already gates on `ls_history.length > 0`
 *  before rendering the chart). */
export function visibleLsMethodologyBreaks(
  rows: readonly MethodologyBreakRow[],
  ls_history: readonly PartyHistoryPoint[],
): MethodologyBreakRow[] {
  if (ls_history.length === 0) return [];
  let first = ls_history[0]!.year;
  let last = ls_history[0]!.year;
  for (const p of ls_history) {
    if (p.year < first) first = p.year;
    if (p.year > last) last = p.year;
  }
  return rows.filter((r) => r.at_year > first && r.at_year <= last);
}

/** Module-level Promise cache for the methodology-breaks catalogue.
 *  The catalogue is tiny (~3KB) and shared across every party page;
 *  a single in-flight fetch suffices for the lifetime of the tab. */
let methodologyBreaksCache: Promise<MethodologyBreakRow[]> | null = null;

/** PR-10: fetch + cache the methodology-breaks catalogue, return only
 *  the LS-relevant subset. A network failure clears the cache so a
 *  subsequent navigation re-issues the fetch; the loader returns an
 *  empty list on failure (defensive - the chart still renders without
 *  markers). */
export function fetchLsMethodologyBreaks(): Promise<MethodologyBreakRow[]> {
  if (methodologyBreaksCache !== null) return methodologyBreaksCache;
  methodologyBreaksCache = fetch(METHODOLOGY_BREAKS_URL)
    .then(async (res) => {
      if (!res.ok) {
        throw new Error(
          `fetch /taxonomy/methodology_breaks.json failed: ${res.status} ${res.statusText}`,
        );
      }
      const catalogue = (await res.json()) as MethodologyBreaksCatalogue;
      return pickLsMethodologyBreaks(catalogue.methodology_breaks ?? []);
    })
    .catch((err) => {
      methodologyBreaksCache = null;
      // Surface the failure to the loader by re-throwing; the party
      // detail loader catches + clears its own cache so a retry
      // re-issues both the marts AND this catalogue.
      throw err;
    });
  return methodologyBreaksCache;
}

async function fetchPartyDetail(
  party_id: string,
  metadata: PartyMeta,
): Promise<PartyDetailViewModel> {
  // Register the two small derived mart files. The backend generator
  // pays the full electoral-corpus scan once at ingest/precompute time;
  // this route reads only rows for the requested party_id. The
  // methodology-breaks catalogue is fetched as a plain JSON in parallel
  // (DuckDB does NOT read this file - it ships as the closed-renderer
  // contract for the LS chart).
  const ls_methodology_breaks_promise = fetchLsMethodologyBreaks().catch(
    () => [] as MethodologyBreakRow[],
  );
  // PR-7: the Current Strength strip reads the same party-page history
  // mart this loader does, so it can run fully in parallel with the
  // existing DuckDB reads. The loader internally registers the CSV +
  // resolves the columns clause via its own boundary; we surface its
  // null sentinel directly when load fails so the strip is suppressed
  // rather than the whole detail page.
  const current_strength_promise = loadPartyCurrentStrength(party_id, {
    is_sentinel: metadata.is_sentinel,
  }).catch(() => null);
  // PR-8: the Alliance Context strip reads party_alliances.csv +
  // history.csv via its own DuckDB boundary; it can run in parallel
  // with the detail loader's own DuckDB reads. A failure surfaces
  // null so the strip is suppressed rather than the whole page.
  const alliance_context_promise = loadPartyAllianceContext(party_id, {
    is_sentinel: metadata.is_sentinel,
  }).catch(() => null);
  // PR-9: the source.csv lookup (Holy Law #9 citation ledger) is
  // shared across every party page; the loader caches it on first
  // call. Run in parallel with the marts.
  const source_lookup_promise = loadSourceLookup();
  // PR-8b D8a: the electoral entities tier + the election-events
  // catalogue power the stronghold-row href derivation. Both are
  // small (~500 KB CSV / ~3 KB JSON), cached at the module level
  // by their respective loaders, and run fully in parallel with
  // the mart fetches. A failure surfaces an empty rows array / a
  // null catalogue so strongholds render as unlinked text rather
  // than breaking the page.
  const electoral_rows_promise = loadConstituencyRows().catch(
    () => [] as readonly ConstituencyEntity[],
  );
  const election_events_promise: Promise<ElectionEventsCatalogue | null> =
    fetchElectionEvents().catch(() => null);
  await Promise.all([
    registerCsvFile(PARTY_HISTORY_URL),
    registerCsvFile(PARTY_STRONGHOLDS_URL),
    registerCsvFile(PARTY_ALLIANCES_URL),
  ]);

  const [historyClause, strongholdsClause, alliancesClause] = await Promise.all(
    [
      csvColumnsClause(PARTY_HISTORY_REL),
      csvColumnsClause(PARTY_STRONGHOLDS_REL),
      csvColumnsClause(PARTY_ALLIANCES_REL),
    ],
  );
  const safePartyId = party_id.replace(/'/g, "''");

  // SUM(BIGINT) in DuckDB promotes to HUGEINT, which duckdb-wasm
  // serializes as a string that JS Number.isFinite() rejects (intOrNull
  // would then coerce to null, then `?? 0` would surface as 0 seats on
  // the citizen-facing headline). CAST back to BIGINT so the result
  // lands as a plain JS bigint that intOrNull handles correctly.
  //
  // PR-9: STRING_AGG(DISTINCT source_ids, '|') folds the per-state
  // source_ids into a pipe-delimited list per cycle. The mart carries
  // one src-XXXX per row, so the post-aggregation distinct count is
  // typically 1 for LS cycles + small (<=N states) for VS cycles.
  const historySql = `
    WITH per_state AS (
      SELECT body, period_label, year, seats, vote_share_pct, contested, party_votes, total_votes, source_ids
      FROM read_csv('${PARTY_HISTORY_URL}', ${historyClause}, header=true)
      WHERE party_id = '${safePartyId}'
    )
    SELECT
      body,
      period_label,
      MIN(year) AS year,
      CAST(SUM(seats) AS BIGINT) AS seats,
      CASE
        WHEN SUM(total_votes) > 0 THEN SUM(party_votes) * 100.0 / SUM(total_votes)
        WHEN COUNT(vote_share_pct) > 0 THEN AVG(vote_share_pct)
        ELSE NULL
      END AS vote_share_pct,
      CAST(SUM(contested) AS BIGINT) AS contested,
      STRING_AGG(DISTINCT source_ids, '|') AS source_ids
    FROM per_state
    GROUP BY body, period_label
    ORDER BY year, period_label
  `;
  const historyRows = await query<RawPartyHistoryMartRow>(historySql);

  const strongholdSql = `
    SELECT
      body,
      rank,
      entity_id,
      constituency_name,
      state,
      wins,
      contested,
      last_won_year,
      results,
      source_ids
    FROM read_csv('${PARTY_STRONGHOLDS_URL}', ${strongholdsClause}, header=true)
    WHERE party_id = '${safePartyId}'
    ORDER BY body, rank
  `;
  const strongholdRows = await query<RawPartyStrongholdMartRow>(strongholdSql);

  const ls_history: PartyHistoryPoint[] = [];
  const vs_history: PartyHistoryPoint[] = [];
  for (const row of historyRows) {
    const point = historyPointFromMart(row);
    if (!point) continue;
    if (row.body === "parliament") ls_history.push(point);
    else if (row.body === "assembly") vs_history.push(point);
  }

  const ls_strongholds: PartyStronghold[] = [];
  const vs_strongholds: PartyStronghold[] = [];
  // PR-8b D8a: resolve the link-context once before the loop so
  // each row gets a synchronous lookup + URL derivation.
  const electoral_rows = await electoral_rows_promise;
  const election_catalogue = await election_events_promise;
  const current_strength = await current_strength_promise;
  const alliance_context = await alliance_context_promise;
  const ls_event_id =
    current_strength?.parliament_latest?.event_id ?? null;
  for (const row of strongholdRows) {
    const stronghold = strongholdFromMart(row);
    if (!stronghold) continue;
    if (row.body === "parliament") {
      ls_strongholds.push(
        attachStrongholdLink(stronghold, "parliament", {
          electoral_rows,
          catalogue: election_catalogue,
          ls_event_id,
        }),
      );
    } else if (row.body === "assembly") {
      vs_strongholds.push(
        attachStrongholdLink(stronghold, "assembly", {
          electoral_rows,
          catalogue: election_catalogue,
          ls_event_id,
        }),
      );
    }
  }

  const totals = computeTotals(ls_history, vs_history);
  const all_ls_methodology_breaks = await ls_methodology_breaks_promise;
  const ls_methodology_breaks = visibleLsMethodologyBreaks(
    all_ls_methodology_breaks,
    ls_history,
  );

  // PR-9: derive source_ids for the two cards that don't surface
  // them on per-row VM data today.
  //
  // alliance_source_ids: DISTINCT source_id over party_alliances
  // rows for this party_id. We run a small dedicated query
  // (4-col + party_id filter) rather than reshape the alliance
  // VM contract. Empty `[]` when alliance_context is null
  // (sentinel + Independent + no-alliance-rows parties).
  let alliance_source_ids: string[] = [];
  if (alliance_context !== null) {
    const allianceSql = `
      SELECT DISTINCT source_id
      FROM read_csv('${PARTY_ALLIANCES_URL}', ${alliancesClause}, header=true)
      WHERE party_id = '${safePartyId}'
        AND source_id IS NOT NULL
        AND length(trim(source_id)) > 0
    `;
    const allianceRows = await query<RawAllianceSourceRow>(allianceSql);
    const seen = new Set<string>();
    for (const r of allianceRows) {
      const sid = (r.source_id ?? "").trim();
      if (sid.length === 0) continue;
      if (seen.has(sid)) continue;
      seen.add(sid);
      alliance_source_ids.push(sid);
    }
  }

  // current_strength_source_ids: union of (a) source_ids on the
  // latest LS cycle + (b) source_ids on the latest VS cycle per
  // state the party contested in. The (a) leg falls out of the
  // already-loaded history; the (b) leg needs a per-state read
  // since the main historySql aggregates state granularity away.
  // Empty `[]` when current_strength is null.
  let current_strength_source_ids: string[] = [];
  if (current_strength !== null) {
    const ids = new Set<string>();
    if (current_strength.parliament_latest !== null && ls_history.length > 0) {
      const latest_ls = ls_history[ls_history.length - 1]!;
      for (const sid of latest_ls.source_ids) ids.add(sid);
    }
    if (current_strength.state_assemblies_latest !== null) {
      const csVsSql = `
        WITH per_state AS (
          SELECT state, year, source_ids
          FROM read_csv('${PARTY_HISTORY_URL}', ${historyClause}, header=true)
          WHERE party_id = '${safePartyId}' AND body = 'assembly'
        ),
        latest AS (
          SELECT state, MAX(year) AS y FROM per_state GROUP BY state
        )
        SELECT DISTINCT p.source_ids
        FROM per_state p
        JOIN latest l ON l.state = p.state AND l.y = p.year
        WHERE p.source_ids IS NOT NULL AND length(trim(p.source_ids)) > 0
      `;
      const csVsRows = await query<{ source_ids: string | null }>(csVsSql);
      for (const r of csVsRows) {
        for (const sid of splitSourceIds(r.source_ids)) ids.add(sid);
      }
    }
    current_strength_source_ids = [...ids];
  }

  const source_lookup = await source_lookup_promise;
  // Build the provenance envelope LAST - it requires every other
  // VM section to be populated. STOP-AND-SURFACE (Holy Law #9):
  // throws when any rendered card has data but resolves zero
  // source_ids. The outer `loadPartyDetail` catches + clears the
  // cache so the page error state surfaces.
  const partialVm = {
    metadata,
    ls_history,
    vs_history,
    ls_strongholds,
    vs_strongholds,
    current_strength,
    alliance_context,
    alliance_source_ids,
    current_strength_source_ids,
  };
  const provenance = buildPartyProvenance(partialVm, source_lookup);

  return {
    metadata,
    ls_history,
    vs_history,
    ls_strongholds,
    vs_strongholds,
    totals,
    ls_methodology_breaks,
    current_strength,
    alliance_context,
    alliance_source_ids,
    current_strength_source_ids,
    provenance,
  };
}

function historyPointFromMart(
  row: RawPartyHistoryMartRow,
): PartyHistoryPoint | null {
  if (!row.period_label || !row.body) return null;
  if (row.body !== "parliament" && row.body !== "assembly") return null;
  return {
    year: intOrNull(row.year) ?? 0,
    period_label: row.period_label,
    seats: intOrNull(row.seats) ?? 0,
    vote_share_pct: numOrNull(row.vote_share_pct),
    contested: intOrNull(row.contested),
    source_ids: splitSourceIds(row.source_ids),
  };
}

function strongholdFromMart(
  row: RawPartyStrongholdMartRow,
): PartyStronghold | null {
  if (!row.entity_id || !row.body) return null;
  if (row.body !== "parliament" && row.body !== "assembly") return null;
  const results = (row.results ?? "")
    .split("")
    .filter((r): r is "W" | "L" => r === "W" || r === "L");
  return {
    entity_id: row.entity_id,
    constituency_name: row.constituency_name ?? "",
    state: row.state ?? "",
    wins: intOrNull(row.wins) ?? 0,
    contested: intOrNull(row.contested) ?? 0,
    last_won_year: intOrNull(row.last_won_year),
    results,
    source_ids: splitSourceIds(row.source_ids),
    // pc_slug + href are derived in a second pass against the
    // canonical electoral.csv entity tier + the election-events
    // catalogue (see `attachStrongholdLink`). Strongholds carry
    // the base shape here so this projection stays pure +
    // synchronously testable.
    pc_slug: null,
    href: null,
  };
}

/** PR-8b D8a: derive `pc_slug` + `href` for a stronghold row.
 *
 *  - `pc_slug` is non-null iff `slugify(constituency_name)` matches
 *    a row in the canonical electoral entity tier at the LATEST
 *    delim cohort for that (state, kind). This is the delim-existence
 *    gate per the brief's E2 cap (the brief explicitly permits an
 *    `entities/electoral.csv` lookup; nothing heavier is used).
 *  - `href` is non-null iff `pc_slug` is non-null AND a target
 *    `event_id` is available for this stronghold's body:
 *      LS -> `current_strength.parliament_latest.event_id` (e.g.
 *            `general-2024`) - applies nationally to every LS row.
 *      VS -> `defaultEventForState(catalogue, state_code)` per the
 *            stronghold's state (e.g. `assembly-2026` for Kerala).
 *
 *  Routes:
 *    - LS -> `link.pc(state, event_id, pc_slug)` (W3b bare-slug
 *      route at main.ts:321; `Constituency.svelte` dispatches PC
 *      vs AC via event prefix).
 *    - VS -> `link.ac(state, constituency_name, event_id)` (legacy
 *      ADR-0052 nested route with `/ac/` literal segment).
 *
 *  Pure; takes everything it needs as parameters so it stays
 *  synchronously testable.
 */
function attachStrongholdLink(
  base: PartyStronghold,
  body: "parliament" | "assembly",
  ctx: {
    electoral_rows: readonly ConstituencyEntity[];
    catalogue: ElectionEventsCatalogue | null;
    ls_event_id: string | null;
  },
): PartyStronghold {
  if (!base.state || !base.constituency_name) return base;
  const kind: "ac" | "pc" = body === "parliament" ? "pc" : "ac";
  const name_slug = slugify(base.constituency_name);
  const hit = resolveConstituencyFromRows(ctx.electoral_rows, {
    state: base.state,
    kind,
    name_slug,
  });
  if (!hit) return base;
  let event_id: string | null = null;
  if (body === "parliament") {
    event_id = ctx.ls_event_id;
  } else {
    // base.state is the LGD slug; election-events keys by ECI
    // state code (S22 etc), so go via `states.codeFromSlug`.
    const state_code = states.codeFromSlug(base.state);
    if (state_code) {
      const evt = defaultEventForState(ctx.catalogue, state_code);
      event_id = evt?.event_id ?? null;
    }
  }
  if (!event_id) return { ...base, pc_slug: name_slug };
  const href =
    body === "parliament"
      ? link.pc(base.state, event_id, name_slug)
      : link.ac(base.state, base.constituency_name, event_id);
  return { ...base, pc_slug: name_slug, href };
}

/** Module-level Promise cache, keyed by party_id. Repeated calls
 *  for the same party return the SAME Promise so the browser pays
 *  the corpus-fetch + DuckDB query exactly once per tab. */
const detailCache = new Map<string, Promise<PartyDetailViewModel | null>>();

/**
 * Load the per-party detail view-model. Returns `null` when the
 * party_id is absent from parties.csv (the page renders the
 * "Party not found" empty state on null). Returns a fully-populated
 * view-model (with possibly-empty arrays for parties with no data
 * in one body) otherwise.
 *
 * Per the canonical-store loader pattern: the cache survives the
 * lifetime of the browser tab; only `__resetForTests` clears it.
 * A fetch failure clears that party's cache entry so a retry
 * re-issues the underlying queries.
 */
export function loadPartyDetail(
  party_id: string | null | undefined,
): Promise<PartyDetailViewModel | null> {
  if (!party_id) return Promise.resolve(null);
  const cached = detailCache.get(party_id);
  if (cached) return cached;
  const promise = (async (): Promise<PartyDetailViewModel | null> => {
    const metadata = await loadPartyMeta(party_id);
    if (!metadata) return null;
    return fetchPartyDetail(party_id, metadata);
  })().catch((err) => {
    detailCache.delete(party_id);
    throw err;
  });
  detailCache.set(party_id, promise);
  return promise;
}

/** Test-only cache reset. NOT exported from index.ts. */
export function __resetForTests(): void {
  detailCache.clear();
  methodologyBreaksCache = null;
}
