"""Rename `state=in_sXX` / `state=in_uXX` partition directories to `state=<lgd-name-slug>`
per ADR-0050 and docs/archive/plans/20260601-lgd-execution-handover.md row M1.

This is the DESIGN + DRY-RUN tool. Execution (rows M2/M3/M4) is gated behind
`--apply` AND requires per-surface reader updates in the same commit (frontend
slug references, CI deploy-site.yml literals, parquet KV_METADATA in manifest,
canonical-store.md examples, etc.) - see
`docs/archive/plans/20260601-lgd-partition-rename-successor-plan.md` for the full blast radius.

Usage:
    python -m tools.migrate.rename_partition_keys --root datasets/boundaries \\
        --manifest .tmp_rename_manifest.json
    python -m tools.migrate.rename_partition_keys --root datasets/boundaries \\
        --manifest .tmp_rename_manifest.json --apply

Produces a JSON manifest of every (old_path, new_path) pair the run would
touch. Default mode is dry-run. `--apply` runs `git mv` for each pair (so the
move shows in git history as a rename, not delete+add).

Slug source: `datasets/taxonomy/lgd_states.json` joined by `eci_st_code`. The
legacy `in_sXX` / `in_uXX` token IS the lowercased ECI st_code with an `in_`
prefix; we strip and uppercase to look up the LGD slug.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
STATES = REPO / "datasets/taxonomy/lgd_states.json"

LEGACY_RE = re.compile(r"state=in_([su]\d{2})$", re.IGNORECASE)


@dataclass(frozen=True)
class RenamePair:
    old: Path
    new: Path
    eci_st_code: str
    lgd_slug: str

    def to_json(self) -> dict:
        return {
            "old": str(self.old.relative_to(REPO)).replace("\\", "/"),
            "new": str(self.new.relative_to(REPO)).replace("\\", "/"),
            "eci_st_code": self.eci_st_code,
            "lgd_slug": self.lgd_slug,
        }


def _load_slug_map() -> dict[str, str]:
    """eci_st_code (uppercase, e.g. S07) -> lgd slug."""
    doc = json.loads(STATES.read_text(encoding="utf-8"))
    return {s["eci_st_code"]: s["slug"] for s in doc["states"]}


def discover(root: Path, slug_map: dict[str, str]) -> list[RenamePair]:
    pairs: list[RenamePair] = []
    for dir_path in root.rglob("state=in_*"):
        if not dir_path.is_dir():
            continue
        m = LEGACY_RE.search(dir_path.name)
        if not m:
            continue
        eci = m.group(1).upper()
        slug = slug_map.get(eci)
        if slug is None:
            raise SystemExit(f"no LGD slug for ECI code {eci!r} (folder {dir_path})")
        new_path = dir_path.parent / f"state={slug}"
        pairs.append(RenamePair(old=dir_path, new=new_path, eci_st_code=eci, lgd_slug=slug))
    return sorted(pairs, key=lambda p: str(p.old))


def write_manifest(pairs: list[RenamePair], out: Path, root: Path) -> None:
    doc = {
        "$comment": (
            "Generated by tools/migrate/rename_partition_keys.py. Each row "
            "binds a legacy `state=in_sXX` partition directory to its "
            "LGD-name-slug equivalent per ADR-0050. Re-runnable; do NOT hand-edit."
        ),
        "root": str(root.relative_to(REPO)).replace("\\", "/"),
        "count": len(pairs),
        "renames": [p.to_json() for p in pairs],
    }
    out.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def apply_pairs(pairs: list[RenamePair]) -> None:
    for p in pairs:
        if p.new.exists():
            raise SystemExit(f"refusing to overwrite existing path {p.new}")
        rel_old = str(p.old.relative_to(REPO))
        rel_new = str(p.new.relative_to(REPO))
        subprocess.run(["git", "mv", rel_old, rel_new], cwd=REPO, check=True)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", required=True, type=Path, help="Folder to scan (e.g. datasets/boundaries)")
    parser.add_argument("--manifest", required=True, type=Path, help="Where to write the rename manifest JSON")
    parser.add_argument("--apply", action="store_true", help="Execute `git mv` for each rename. Default: dry-run only.")
    args = parser.parse_args(argv)

    root = (REPO / args.root).resolve() if not args.root.is_absolute() else args.root
    if not root.exists():
        raise SystemExit(f"root not found: {root}")

    slug_map = _load_slug_map()
    pairs = discover(root, slug_map)
    write_manifest(pairs, args.manifest, root)
    print(f"discovered {len(pairs)} rename pairs under {root.relative_to(REPO)}", file=sys.stderr)
    print(f"manifest written to {args.manifest}", file=sys.stderr)
    if args.apply:
        apply_pairs(pairs)
        print(f"applied {len(pairs)} renames via `git mv`", file=sys.stderr)
    else:
        print("DRY RUN - no files moved. Re-run with --apply to execute.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
