"""Dedupe ``parties.csv`` self-duplicates and legit dual-spelling pairs (PR-Q1 / PR-Q1b).

Run from the repo root:

    python -m tools.dedupe_parties_csv                      # dry-run (Class A only)
    python -m tools.dedupe_parties_csv --apply              # merge Class A
    python -m tools.dedupe_parties_csv --include-class-c    # dry-run (A + C)
    python -m tools.dedupe_parties_csv --include-class-c --apply  # merge A + C

Background
----------

The PR #952 correlator (2026-06-09) minted NEW ``parties.csv`` rows for
publisher labels that already had a row carrying the same ``full`` value,
producing same-``full``-different-``party_id`` pairs that the central
resolver cannot tell apart. PR-Q1 commit 2 adds a ``full``-name fallback
to ``party_resolver.load_resolver``; that fallback's collision-set rule
WOULD silently drop these duplicates from the by_alias index unless the
collisions are cleaned up first. This tool is commit 1 of PR-Q1: it merges
the PR #952 self-dupes into the pre-existing canonical rows and rewrites
every ``party_id`` FK across the corpus.

Collision-set classification
----------------------------

Audit of ``datasets/data/entities/parties.csv`` (2026-06-11) found 11
distinct ``full`` values appearing in more than one non-sentinel row. They
fall into three classes:

  - Class A (PR #952 self-duplicates) - the curator-confirmed pairs in
    ``CLASS_A_DUPLICATES`` below. The tool merges these into the canonical
    row and deletes the duplicate. Per the Fowler tiebreaker rule
    (`pick the row whose ``short`` is shorter; on tie, prefer the row
    without dashes/spaces; on tie, prefer the row with more aliases /
    older-looking party_id`), the canonical is the SHORTER, NO-DASH row.

  - Class B (sentinel-placeholder ``full`` values: ``NA'S`` /
    ``EXPANDED PARTY NAME NOT RELEASED BY THE ECI`` / ``UNKNOWN PARTY``).
    These are NOT identity collisions; they are 60 distinct parties whose
    ``full`` was never recorded by the publisher and got back-filled with a
    sentinel string. The tool LEAVES them alone; the resolver's
    ``_SENTINEL_FULL_PLACEHOLDERS`` skiplist (commit 2) keeps them out of
    the by_alias index so they never collide.

  - Class C (legitimate dual-spelling collisions: AJSU/AJSUP, JJP/JNJP,
    RLP/RALTP, ICSP/ICP, SKPP/SRPP, AD(S)/ADAL). PR-Q1b (2026-06-12)
    adds the ``CLASS_C_CURATED_PAIRS`` map and the ``--include-class-c``
    CLI flag so the tool merges these pairs too when invoked with the
    flag. The canonical pid in each pair is chosen with an EXTRA
    preference for the ECI-standard short over the publisher variant
    (e.g. AD(S) over ADAL, AJSU over AJSUP); see the inline comments on
    ``CLASS_C_CURATED_PAIRS`` for the per-pair rationale. Unlike Class A,
    the Fowler tiebreaker cross-check does NOT run on Class C - the
    curator pick reflects ECI-domain knowledge (publisher abbreviation
    standards) that the algorithm does not encode.

Ordering note (dedupe <-> correlate_unk_apply)
-----------------------------------------------

A ``verdict.csv`` generated by this tool BEFORE a fresh dedupe run may
list a ``delete_pid`` that has already been removed. The follow-on
``tools.correlate_unk_apply`` reader skips any row whose ``delete_pid``
is not present in the current parties.csv (logged, not raised); re-running
this tool to regenerate the verdict ahead of correlate_unk_apply is the
recommended hygiene step.
"""

from __future__ import annotations

import argparse
import csv
import io
import re
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Final


REPO_ROOT = Path(__file__).resolve().parents[2]

#: Long-format electoral CSV indicator_ids whose ``value_text`` is itself a
#: ``party_id`` FK (mirror of ``backend.tests.test_party_id_fk_closure.
#: PARTY_ID_INDICATOR_RE``). All other rows in those CSVs hold numeric
#: observations in ``value_numeric`` and are not subject to FK rewrite.
ELECTORAL_PARTY_ID_INDICATOR_RE: Final[re.Pattern[str]] = re.compile(
    r"^(ac|pc|state)-(winner|leading|runnerup)-party-id$"
)
PARTIES_CSV = REPO_ROOT / "datasets" / "data" / "entities" / "parties.csv"


#: Sentinel-placeholder ``full`` values that are NOT identity collisions.
#: Mirrors the resolver's ``_SENTINEL_FULL_PLACEHOLDERS`` constant (commit 2).
SENTINEL_FULL_PLACEHOLDERS: Final[frozenset[str]] = frozenset({
    "NA'S",
    "EXPANDED PARTY NAME NOT RELEASED BY THE ECI",
    "UNKNOWN PARTY",
})


#: Class A: PR #952 self-duplicates. Each tuple is (delete_pid, keep_pid).
#: The keep_pid is the row that survives; the delete_pid's aliases + any
#: empty-on-keep fields are merged into it before the delete_pid row is
#: removed and its FK references across the corpus are rewritten.
#:
#: The Fowler tiebreaker rule (docstring) selects the canonical
#: algorithmically; the explicit list here is the human-confirmed audit
#: (brief 2026-06-11) and acts as a guard against the tool silently picking
#: the wrong side on a future re-run when a new collision lands.
CLASS_A_DUPLICATES: Final[tuple[tuple[str, str], ...]] = (
    ("parties.IN.UTTAMA_PRAJAAKEEYA_PARTY", "parties.IN.UPJP"),
    ("parties.IN.GARVI_GUJARAT_PARTY", "parties.IN.GAGUP"),
    ("parties.IN.AAAAP", "parties.IN.AAAP"),
)


#: Class C: legit dual-spelling pairs - two parties.csv rows share the same
#: ``full`` value because the publisher minted two abbreviations for the
#: SAME real-world party. PR-Q1b (2026-06-12). Each entry is
#: ``delete_pid -> keep_pid``; the inline comment names the source-of-truth
#: for the canonical pick. Processed only when the CLI is invoked with
#: ``--include-class-c``.
#:
#: Verification (Phase 1, brief 2026-06-12):
#:   - All 6 fulls are confirmed via the on-disk parties.csv + the TCPD
#:     parties-parity verdict (datasets/ephemeral/party-parity/tcpd-parties/
#:     2021/48f7c83c/verdict.csv) which lists ICP + ICSP both with the
#:     identical full ``INDIAN CHRISTIAN SECULAR PARTY`` (ext keys 3342 +
#:     3344) and SKPP + SRPP both with the identical full ``SIKKIM
#:     REPUBLICAN PARTY`` (ext keys 17266 + 24897).
#:   - Candidacy state-overlap: ICSP+ICP both in karnataka + IN;
#:     SKPP+SRPP both in sikkim/2019; JJP+JNJP both label Hanuman-Beniwal-
#:     style Haryana party (JNJP holds the bulk in haryana/2019);
#:     AJSU+AJSUP both label the Jharkhand Sudesh-Mahto party;
#:     RLP+RALTP both in rajasthan; ADS+ADAL both label Apna Dal
#:     (Soneylal). See the PR body for the full per-pair candidacy table.
#:
#: Unlike Class A, the Fowler tiebreaker does NOT cross-check these picks:
#: the curator pick reflects ECI-publisher standards (AD(S) is the official
#: ECI form; AJSU is the older ECI label vs AJSUP) that Fowler does not
#: encode. The SKPP-over-SRPP and ICSP-over-ICP picks are reinforced by
#: Fowler (more aliases / more curated row); the AD(S)-over-ADAL and
#: JJP-over-JNJP picks override Fowler's bare ``shorter wins`` rule.
CLASS_C_CURATED_PAIRS: Final[dict[str, str]] = {
    # JNJP is a publisher variant; JJP is the ECI standard short for the
    # Haryana-based Jannayak Janta Party (Dushyant Chautala, founded 2018).
    "parties.IN.JNJP": "parties.IN.JJP",
    # AJSUP is the TCPD/publisher variant (TCPD: ``AJSU PARTY``); AJSU is
    # the older ECI label for the Jharkhand-based All Jharkhand Students
    # Union (Sudesh Mahto, founded 1986). AJSU's row carries the Wikipedia
    # link confirming the identity.
    "parties.IN.AJSUP": "parties.IN.AJSU",
    # RALTP is the publisher variant; RLP is the ECI standard short for
    # the Rajasthan-based Rashtriya Loktantrik Party (Hanuman Beniwal,
    # founded 2018).
    "parties.IN.RALTP": "parties.IN.RLP",
    # Both ICP + ICSP are listed in TCPD 2021 with identical full
    # ``INDIAN CHRISTIAN SECULAR PARTY`` (ext keys 3342 + 3344). ICSP has
    # 58 candidacies + the ``INDIAN CHRISTIAN SECULAR PARTY`` alias
    # already curated; ICP has 2 candidacies and no aliases. Keep ICSP.
    "parties.IN.ICP": "parties.IN.ICSP",
    # Both SKPP + SRPP are listed in TCPD 2021 with identical full
    # ``SIKKIM REPUBLICAN PARTY`` (ext keys 17266 + 24897); both have
    # candidacies in sikkim/2019. SKPP has the ``SIKKIM REPUBLICAN PARTY``
    # alias already curated + 12 candidacies vs SRPP's 3. Keep SKPP
    # (Fowler tiebreaker favours the more-curated row; brief originally
    # suggested SRPP as the initialism but was overridden by Phase-1
    # evidence per brief's flip-allowance rule).
    "parties.IN.SRPP": "parties.IN.SKPP",
    # ADAL is the publisher abbreviation; AD(S) is the official ECI form
    # carrying the parenthetical (Soneylal) distinguishing it from Apna
    # Dal (Kameraj). ADS holds the ECI-canonical short ``AD(S)``; ADAL has
    # the historical home_state_codes (IN-MP|IN-UP) which merges into ADS
    # via the INHERITABLE_FIELDS pathway.
    "parties.IN.ADAL": "parties.IN.ADS",
}


# Fields on parties.csv (schema v1.1). Used for the merge logic below.
PARTIES_COLUMNS: Final[tuple[str, ...]] = (
    "party_id",
    "short",
    "full",
    "eci_codes",
    "brand_colour",
    "symbol_asset",
    "wikipedia",
    "aliases",
    "recognition_scope",
    "home_state_codes",
    "founded_year",
    "dissolved_year",
    "predecessor_party_ids",
    "successor_party_ids",
    "name_history",
    "claims_to_parent_name",
    "name_native_script",
    "is_sentinel",
)

# Fields where the canonical (keep) row inherits the duplicate's value
# only when the canonical's own value is empty. ``aliases`` is handled
# separately (union + sort). ``party_id`` / ``short`` / ``full`` /
# ``is_sentinel`` are the identity columns and are NEVER inherited.
INHERITABLE_FIELDS: Final[tuple[str, ...]] = (
    "eci_codes",
    "brand_colour",
    "symbol_asset",
    "wikipedia",
    "recognition_scope",
    "home_state_codes",
    "founded_year",
    "dissolved_year",
    "predecessor_party_ids",
    "successor_party_ids",
    "name_history",
    "claims_to_parent_name",
    "name_native_script",
)


def _fowler_winner(rows: list[dict[str, str]]) -> dict[str, str]:
    """Apply the Fowler tiebreaker to pick the canonical row.

    Rule (docstring): shorter ``short`` wins; on tie, prefer the row
    without dashes or spaces in ``short``; on tie, prefer the row with
    more aliases / older-looking party_id (proxied as the row whose
    ``party_id`` sorts EARLIEST alphabetically, which favours older /
    shorter / less-suffixed ids).
    """
    def key(r: dict[str, str]) -> tuple[int, int, int, str]:
        short = (r.get("short") or "")
        aliases = [a for a in (r.get("aliases") or "").split("|") if a.strip()]
        has_dash_or_space = 1 if (" " in short or "-" in short) else 0
        return (
            len(short),
            has_dash_or_space,
            -len(aliases),
            r.get("party_id") or "",
        )
    return min(rows, key=key)


def _read_parties(path: Path) -> tuple[list[str], list[dict[str, str]]]:
    with path.open(encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        fieldnames = list(reader.fieldnames or [])
        rows = list(reader)
    return fieldnames, rows


def _write_csv(
    path: Path, fieldnames: list[str], rows: list[dict[str, str]]
) -> None:
    buf = io.StringIO(newline="")
    writer = csv.DictWriter(buf, fieldnames=fieldnames, lineterminator="\n")
    writer.writeheader()
    for row in rows:
        writer.writerow({k: row.get(k, "") for k in fieldnames})
    path.write_text(buf.getvalue(), encoding="utf-8", newline="")


def _merge_aliases(canonical: dict[str, str], duplicate: dict[str, str]) -> str:
    """Return the merged ``aliases`` cell for the canonical row.

    Union of canonical.aliases U duplicate.aliases U {duplicate.short};
    upper-cased dedupe, sorted lexicographically, pipe-joined. The
    duplicate's short is preserved as an alias so the resolver's existing
    alias-lookup path still resolves any publisher label that historically
    pointed to the duplicate's id.
    """
    merged: set[str] = set()
    for raw in (
        canonical.get("aliases") or "",
        duplicate.get("aliases") or "",
        duplicate.get("short") or "",
    ):
        for token in str(raw).split("|"):
            cleaned = token.strip()
            if cleaned:
                merged.add(cleaned)
    return "|".join(sorted(merged))


def _scan_collisions(
    rows: list[dict[str, str]],
) -> dict[str, list[dict[str, str]]]:
    """Group non-sentinel rows by upper-cased ``full`` and keep only sets
    of size > 1. Rows missing ``full`` are skipped (no collision possible).
    """
    by_full: dict[str, list[dict[str, str]]] = {}
    for r in rows:
        if (r.get("is_sentinel") or "").strip().lower() == "true":
            continue
        full = (r.get("full") or "").strip().upper()
        if not full:
            continue
        by_full.setdefault(full, []).append(r)
    return {f: rs for f, rs in by_full.items() if len(rs) > 1}


def _classify(
    full: str, members: list[dict[str, str]]
) -> tuple[str, str | None]:
    """Return (class_letter, note).

    Class A iff a ``(delete_pid, keep_pid)`` pair from ``CLASS_A_DUPLICATES``
    is exactly represented among the members; Class C iff a corresponding
    pair appears in ``CLASS_C_CURATED_PAIRS``; otherwise Class B (sentinel
    placeholder) or unclassified (returned as Class C with the deferred
    note - the unclassified case is treated as Class C for reporting only).
    """
    if full in SENTINEL_FULL_PLACEHOLDERS:
        return "B", "sentinel-placeholder full (60 affected rows skiplisted)"
    pids = {r.get("party_id") for r in members}
    for delete_pid, keep_pid in CLASS_A_DUPLICATES:
        if delete_pid in pids and keep_pid in pids:
            return "A", f"PR #952 self-duplicate; keep {keep_pid}, delete {delete_pid}"
    for delete_pid, keep_pid in CLASS_C_CURATED_PAIRS.items():
        if delete_pid in pids and keep_pid in pids:
            return "C", f"curated dual-spelling; keep {keep_pid}, delete {delete_pid}"
    return "C", "legit dual-spelling; defer to Hans+Max party-lineage review"


def _candidacy_paths() -> list[Path]:
    assembly = sorted(
        (REPO_ROOT / "datasets" / "elections" / "assembly").glob(
            "state=*/election=*/candidacies.csv"
        )
    )
    parliament = sorted(
        (REPO_ROOT / "datasets" / "elections" / "parliament").glob(
            "election=*/candidacies.csv"
        )
    )
    return assembly + parliament


def _summary_paths() -> list[Path]:
    assembly = sorted(
        (REPO_ROOT / "datasets" / "elections" / "assembly").glob(
            "state=*/election=*/summary.csv"
        )
    )
    parliament = sorted(
        (REPO_ROOT / "datasets" / "elections" / "parliament").glob(
            "election=*/summary.csv"
        )
    )
    return assembly + parliament


def _electoral_result_paths() -> list[Path]:
    return sorted(
        (REPO_ROOT / "datasets" / "data" / "datapoints" / "electoral").glob(
            "*_election_results.csv"
        )
    )


def _party_alliances_path() -> Path:
    return REPO_ROOT / "datasets" / "data" / "entities" / "party_alliances.csv"


def _rewrite_fk_in_file(
    path: Path,
    fk_map: dict[str, str],
    columns: list[str],
    *,
    apply: bool,
) -> int:
    """Rewrite the named ``columns`` in ``path`` where the value is a key
    of ``fk_map``. Returns the number of cells changed. Skips files whose
    header does not contain ANY of the requested columns.
    """
    if not path.exists():
        return 0
    fieldnames, rows = _read_parties(path)  # generic CSV read
    cols_present = [c for c in columns if c in fieldnames]
    if not cols_present:
        return 0
    changes = 0
    for row in rows:
        for col in cols_present:
            v = (row.get(col) or "").strip()
            if v in fk_map:
                row[col] = fk_map[v]
                changes += 1
    if changes and apply:
        _write_csv(path, fieldnames, rows)
    return changes


def _rewrite_electoral_value_text_fk(
    path: Path, fk_map: dict[str, str], *, apply: bool,
) -> int:
    """Rewrite ``value_text`` cells in a long-format electoral CSV when
    the row's ``indicator_id`` matches ``ELECTORAL_PARTY_ID_INDICATOR_RE``
    and the value is a key of ``fk_map``. Returns the number of cells
    changed.

    The long-format electoral CSV at
    ``datasets/data/datapoints/electoral/<slug>_election_results.csv``
    holds one observation per row keyed by ``(entity_id, year, period_label,
    period_seq, indicator_id)``; the value lives in ``value_text`` for
    ``*-(winner|leading|runnerup)-party-id`` indicators and in
    ``value_numeric`` for everything else. The generic
    ``_rewrite_fk_in_file`` cannot handle this case because the column name
    that carries the party_id is the same generic ``value_text`` used by
    every other string-valued indicator; this function adds the
    indicator-id filter so non-party rows are never touched.
    """
    if not path.exists():
        return 0
    fieldnames, rows = _read_parties(path)
    if "value_text" not in fieldnames or "indicator_id" not in fieldnames:
        return 0
    changes = 0
    for row in rows:
        indicator = (row.get("indicator_id") or "").strip()
        if not ELECTORAL_PARTY_ID_INDICATOR_RE.match(indicator):
            continue
        v = (row.get("value_text") or "").strip()
        if v in fk_map:
            row["value_text"] = fk_map[v]
            changes += 1
    if changes and apply:
        _write_csv(path, fieldnames, rows)
    return changes


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--apply",
        action="store_true",
        help=(
            "Apply the merge to parties.csv + FK rewrites across the corpus."
            " Default is dry-run (verdict.csv only)."
        ),
    )
    parser.add_argument(
        "--include-class-c",
        action="store_true",
        help=(
            "Also process the Class C curated dual-spelling pairs from"
            " CLASS_C_CURATED_PAIRS (PR-Q1b, 2026-06-12). Default OFF."
        ),
    )
    args = parser.parse_args()

    fieldnames, rows = _read_parties(PARTIES_CSV)
    by_pid = {(r.get("party_id") or "").strip(): r for r in rows}
    collisions = _scan_collisions(rows)

    # Each action tuple: (class_letter, delete_pid, keep_pid, canonical_row, duplicate_row).
    merge_actions: list[tuple[str, str, str, dict[str, str], dict[str, str]]] = []
    classified: dict[str, list[tuple[str, str | None, list[str]]]] = {
        "A": [], "B": [], "C": [],
    }
    for full, members in sorted(collisions.items()):
        cls, note = _classify(full, members)
        pids = sorted((r.get("party_id") or "") for r in members)
        classified[cls].append((full, note, pids))
        if cls == "A":
            # Determine the brief-named keep + delete from CLASS_A_DUPLICATES.
            keep_pid = next(
                keep for (delete, keep) in CLASS_A_DUPLICATES
                if any(r.get("party_id") == delete for r in members)
                and any(r.get("party_id") == keep for r in members)
            )
            delete_pid = next(
                delete for (delete, keep) in CLASS_A_DUPLICATES
                if any(r.get("party_id") == delete for r in members)
                and any(r.get("party_id") == keep for r in members)
            )
            canonical_row = by_pid[keep_pid]
            duplicate_row = by_pid[delete_pid]
            # Cross-check the brief's named winner against the Fowler tiebreaker.
            fowler_pick = _fowler_winner([canonical_row, duplicate_row])
            if fowler_pick.get("party_id") != keep_pid:
                raise RuntimeError(
                    f"Fowler tiebreaker disagrees with curator: full={full!r} "
                    f"brief named keep={keep_pid!r} but algorithm picked "
                    f"{fowler_pick.get('party_id')!r}. Re-audit before --apply."
                )
            merge_actions.append(
                ("A", delete_pid, keep_pid, canonical_row, duplicate_row)
            )
        elif cls == "C" and args.include_class_c:
            # Find the matching curated pair. Class C does NOT cross-check
            # against Fowler: the curator pick reflects ECI-publisher
            # standards (AD(S) over ADAL, AJSU over AJSUP) that the
            # algorithm does not encode.
            curated = None
            for delete_pid, keep_pid in CLASS_C_CURATED_PAIRS.items():
                if any(r.get("party_id") == delete_pid for r in members) and \
                        any(r.get("party_id") == keep_pid for r in members):
                    curated = (delete_pid, keep_pid)
                    break
            if curated is None:
                # Unclassified Class C (not in CLASS_C_CURATED_PAIRS).
                # Skip - still requires curator review.
                continue
            delete_pid, keep_pid = curated
            canonical_row = by_pid[keep_pid]
            duplicate_row = by_pid[delete_pid]
            merge_actions.append(
                ("C", delete_pid, keep_pid, canonical_row, duplicate_row)
            )

    print(f"=== parties.csv collision audit ===")
    print(f"total rows: {len(rows)}")
    print(f"distinct collision sets (full count > 1): {len(collisions)}")
    print(f"  Class A (PR #952 self-dupes, ACTIONABLE): {len(classified['A'])}")
    for full, note, pids in classified["A"]:
        print(f"    {full!r} -> {pids}  ({note})")
    print(f"  Class B (sentinel placeholders, SKIPPED): {len(classified['B'])}")
    for full, note, pids in classified["B"]:
        print(f"    {full!r}: {len(pids)} rows  ({note})")
    c_label = (
        "ACTIONABLE" if args.include_class_c else "SKIPPED (pass --include-class-c)"
    )
    print(f"  Class C (legit dual-spelling, {c_label}): {len(classified['C'])}")
    for full, note, pids in classified["C"]:
        print(f"    {full!r} -> {pids}  ({note})")

    # Compute the FK-rewrite map (covers both Class A and Class C actions).
    fk_map = {delete: keep for (_, delete, keep, _, _) in merge_actions}

    # Build the verdict rows BEFORE any disk edits.
    verdict_rows: list[dict[str, str]] = []

    # Pre-scan FK count per delete_pid for verdict reporting.
    fk_count_by_pid: Counter[str] = Counter()
    for path in _candidacy_paths():
        with path.open(encoding="utf-8", newline="") as fh:
            for row in csv.DictReader(fh):
                pid = (row.get("party_id") or "").strip()
                if pid in fk_map:
                    fk_count_by_pid[pid] += 1
    for path in _summary_paths():
        with path.open(encoding="utf-8", newline="") as fh:
            for row in csv.DictReader(fh):
                for col in ("winner_party_id", "runnerup_party_id"):
                    v = (row.get(col) or "").strip()
                    if v in fk_map:
                        fk_count_by_pid[v] += 1
    for path in _electoral_result_paths():
        with path.open(encoding="utf-8", newline="") as fh:
            for row in csv.DictReader(fh):
                indicator = (row.get("indicator_id") or "").strip()
                if not ELECTORAL_PARTY_ID_INDICATOR_RE.match(indicator):
                    continue
                pid = (row.get("value_text") or "").strip()
                if pid in fk_map:
                    fk_count_by_pid[pid] += 1
    alli = _party_alliances_path()
    if alli.exists():
        with alli.open(encoding="utf-8", newline="") as fh:
            for row in csv.DictReader(fh):
                for col in ("party_id", "alliance_party_id"):
                    v = (row.get(col) or "").strip()
                    if v in fk_map:
                        fk_count_by_pid[v] += 1

    for cls, delete_pid, keep_pid, canonical_row, duplicate_row in merge_actions:
        merged_aliases = _merge_aliases(canonical_row, duplicate_row)
        canon_pre = (canonical_row.get("aliases") or "").strip()
        canon_pre_set = {
            t.strip() for t in canon_pre.split("|") if t.strip()
        }
        new_aliases_added = sum(
            1 for t in merged_aliases.split("|")
            if t and t not in canon_pre_set
        )
        verdict_rows.append({
            "class": cls,
            "delete_pid": delete_pid,
            "keep_pid": keep_pid,
            "full": (canonical_row.get("full") or "").upper(),
            "alias_count_added": str(new_aliases_added),
            "rows_to_rewrite": str(fk_count_by_pid.get(delete_pid, 0)),
        })

    # Emit verdict.csv (always, dry-run included).
    # Reproducible id: timestamp at minute granularity is enough for
    # tracking; full microsecond would create unnecessary churn.
    run_id = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    verdict_dir = (
        REPO_ROOT / "datasets" / "ephemeral" / "parties-dedupe" / run_id
    )
    verdict_dir.mkdir(parents=True, exist_ok=True)
    verdict_path = verdict_dir / "verdict.csv"
    _write_csv(
        verdict_path,
        ["class", "delete_pid", "keep_pid", "full", "alias_count_added", "rows_to_rewrite"],
        verdict_rows,
    )
    print()
    print(f"verdict.csv -> {verdict_path.relative_to(REPO_ROOT).as_posix()}")
    for row in verdict_rows:
        print(
            f"  [{row['class']}] {row['delete_pid']} -> {row['keep_pid']}  "
            f"aliases_added={row['alias_count_added']}  "
            f"rows_to_rewrite={row['rows_to_rewrite']}"
        )

    if not args.apply:
        print()
        print("DRY-RUN complete. Pass --apply to perform the merge.")
        return 0

    # APPLY mode: edit parties.csv + walk corpus + rewrite FKs.
    delete_pids = {d for _, d, _, _, _ in merge_actions}
    new_parties_rows: list[dict[str, str]] = []
    for row in rows:
        pid = (row.get("party_id") or "").strip()
        if pid in delete_pids:
            continue  # drop the duplicate
        # If this is a keep_pid that received a merge, write the updated row.
        for _, delete_pid, keep_pid, canonical_row, duplicate_row in merge_actions:
            if pid != keep_pid:
                continue
            new_aliases = _merge_aliases(canonical_row, duplicate_row)
            row["aliases"] = new_aliases
            for field in INHERITABLE_FIELDS:
                canon_val = (row.get(field) or "").strip()
                dup_val = (duplicate_row.get(field) or "").strip()
                if not canon_val and dup_val:
                    row[field] = dup_val
            break
        new_parties_rows.append(row)

    _write_csv(PARTIES_CSV, fieldnames, new_parties_rows)
    print()
    print(
        f"parties.csv: deleted {len(delete_pids)} rows, updated "
        f"{len(merge_actions)} canonical rows."
    )

    # Walk corpus and rewrite FKs.
    rewrite_stats: Counter[str] = Counter()
    for path in _candidacy_paths():
        n = _rewrite_fk_in_file(path, fk_map, ["party_id"], apply=True)
        if n:
            rewrite_stats["candidacies_cells"] += n
            rewrite_stats["candidacies_files"] += 1
    for path in _summary_paths():
        n = _rewrite_fk_in_file(
            path, fk_map, ["winner_party_id", "runnerup_party_id"], apply=True
        )
        if n:
            rewrite_stats["summary_cells"] += n
            rewrite_stats["summary_files"] += 1
    for path in _electoral_result_paths():
        # Long-format CSV: party_id FK lives in ``value_text`` (filtered by
        # the indicator_id regex). The legacy ``party_id`` column does not
        # exist on these files; using the indicator-aware rewriter is the
        # only structural path (mirrors the FK closure test's contract).
        n = _rewrite_electoral_value_text_fk(path, fk_map, apply=True)
        if n:
            rewrite_stats["electoral_results_cells"] += n
            rewrite_stats["electoral_results_files"] += 1
    if _party_alliances_path().exists():
        n = _rewrite_fk_in_file(
            _party_alliances_path(),
            fk_map,
            ["party_id", "alliance_party_id"],
            apply=True,
        )
        if n:
            rewrite_stats["party_alliances_cells"] += n
            rewrite_stats["party_alliances_files"] += 1

    print()
    print(f"FK rewrites applied:")
    for k in (
        "candidacies_cells",
        "summary_cells",
        "electoral_results_cells",
        "party_alliances_cells",
    ):
        if rewrite_stats[k]:
            files_key = k.replace("_cells", "_files")
            print(
                f"  {k}: {rewrite_stats[k]} cells across "
                f"{rewrite_stats[files_key]} files"
            )
    print(f"  TOTAL cells: {sum(v for k, v in rewrite_stats.items() if k.endswith('_cells'))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
